server:
  port: 8765
spring:
  application:
    name: cloud-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: client-feign
